idf_component_register(
    SRCS 
        "src/main.c" 
        "src/ble_spp_server.c" 
        "src/adc.c"
        "src/crc.c"
        "src/buffer.c"
        "src/bldc_interface.c"
        "src/bldc_interface_uart.c"
        "src/packet.c"
        "src/led.c"
        "src/bms.c"
    INCLUDE_DIRS
        "."
        "include"
)